In [1]:
import os
from glob import glob
import pandas as pd
from functools import reduce
from xml.etree import ElementTree as et

In [32]:
#load all xml files and store in a list
xmlfiles = glob('./data_images/*.xml')
#data cleaning. replace\\ with /
replace_text = lambda x: x.replace('\\','/')
xmlfiles = list(map(replace_text,xmlfiles))

In [33]:
xmlfiles

['./data_images/c1.xml',
 './data_images/c10.xml',
 './data_images/c11.xml',
 './data_images/c12.xml',
 './data_images/c13.xml',
 './data_images/c14.xml',
 './data_images/c15.xml',
 './data_images/c16.xml',
 './data_images/c17.xml',
 './data_images/c18.xml',
 './data_images/c19.xml',
 './data_images/c2.xml',
 './data_images/c20.xml',
 './data_images/c21.xml',
 './data_images/c22.xml',
 './data_images/c23.xml',
 './data_images/c24.xml',
 './data_images/c25.xml',
 './data_images/c26.xml',
 './data_images/c27.xml',
 './data_images/c28.xml',
 './data_images/c29.xml',
 './data_images/c3.xml',
 './data_images/c30.xml',
 './data_images/c31.xml',
 './data_images/c32.xml',
 './data_images/c33.xml',
 './data_images/c34.xml',
 './data_images/c35.xml',
 './data_images/c36.xml',
 './data_images/c37.xml',
 './data_images/c38.xml',
 './data_images/c39.xml',
 './data_images/c4.xml',
 './data_images/c40.xml',
 './data_images/c41.xml',
 './data_images/c42.xml',
 './data_images/c43.xml',
 './data_images/c44.xml',
 './data_images/c45.xml',
 './data_images/c46.xml',
 './data_images/c47.xml',
 './data_images/c48.xml',
 './data_images/c49.xml',
 './data_images/c5.xml',
 './data_images/c50.xml',
 './data_images/c6.xml',
 './data_images/c7.xml',
 './data_images/c8.xml',
 './data_images/c9.xml',
 './data_images/g1.xml',
 './data_images/g10.xml',
 './data_images/g11.xml',
 './data_images/g12.xml',
 './data_images/g13.xml',
 './data_images/g14.xml',
 './data_images/g15.xml',
 './data_images/g16.xml',
 './data_images/g17.xml',
 './data_images/g18.xml',
 './data_images/g19.xml',
 './data_images/g2.xml',
 './data_images/g20.xml',
 './data_images/g21.xml',
 './data_images/g22.xml',
 './data_images/g23.xml',
 './data_images/g24.xml',
 './data_images/g25.xml',
 './data_images/g26.xml',
 './data_images/g27.xml',
 './data_images/g28.xml',
 './data_images/g29.xml',
 './data_images/g3.xml',
 './data_images/g30.xml',
 './data_images/g31.xml',
 './data_images/g32.xml',
 './data_images/g33.xml',
 './data_images/g34.xml',
 './data_images/g35.xml',
 './data_images/g36.xml',
 './data_images/g37.xml',
 './data_images/g38.xml',
 './data_images/g39.xml',
 './data_images/g40.xml',
 './data_images/g41.xml',
 './data_images/g42.xml',
 './data_images/g43.xml',
 './data_images/g44.xml',
 './data_images/g45.xml',
 './data_images/g46.xml',
 './data_images/g47.xml',
 './data_images/g48.xml',
 './data_images/g49.xml',
 './data_images/g5.xml',
 './data_images/g50.xml',
 './data_images/g6.xml',
 './data_images/g7.xml',
 './data_images/g8.xml',
 './data_images/g9.xml',
 './data_images/t1.xml',
 './data_images/t10.xml',
 './data_images/t11.xml',
 './data_images/t12.xml',
 './data_images/t13.xml',
 './data_images/t14.xml',
 './data_images/t15.xml',
 './data_images/t16.xml',
 './data_images/t17.xml',
 './data_images/t18.xml',
 './data_images/t19.xml',
 './data_images/t2.xml',
 './data_images/t20.xml',
 './data_images/t21.xml',
 './data_images/t22.xml',
 './data_images/t23.xml',
 './data_images/t24.xml',
 './data_images/t25.xml',
 './data_images/t26.xml',
 './data_images/t27.xml',
 './data_images/t28.xml',
 './data_images/t29.xml',
 './data_images/t3.xml',
 './data_images/t30.xml',
 './data_images/t31.xml',
 './data_images/t32.xml',
 './data_images/t33.xml',
 './data_images/t34.xml',
 './data_images/t35.xml',
 './data_images/t36.xml',
 './data_images/t37.xml',
 './data_images/t38.xml',
 './data_images/t39.xml',
 './data_images/t4.xml',
 './data_images/t40.xml',
 './data_images/t41.xml',
 './data_images/t42.xml',
 './data_images/t43.xml',
 './data_images/t44.xml',
 './data_images/t45.xml',
 './data_images/t46.xml',
 './data_images/t47.xml',
 './data_images/t48.xml',
 './data_images/t49.xml',
 './data_images/t5.xml',
 './data_images/t50.xml',
 './data_images/t6.xml',
 './data_images/t7.xml',
 './data_images/t8.xml',
 './data_images/t9.xml']

In [28]:
def extract_text(filename):
    tree = et.parse(filename)
    root = tree.getroot()

    image_name = root.find('filename').text
    width = root.find('size').find('width').text
    height = root.find('size').find('height').text
    objs = root.findall('object')
    parser = [] 
    for obj in objs:
        name = obj.find('name').text
        bndbox = obj.find('bndbox')
        xmin = bndbox.find('xmin').text
        xmax = bndbox.find('xmax').text
        ymin = bndbox.find('ymin').text
        ymax = bndbox.find('ymax').text
        parser.append([image_name, width, height, name, xmin,xmax,ymin,ymax])

    return parser

In [35]:
parser_all = list(map(extract_text,xmlfiles))

In [36]:
parser_all

[[['c1.jpg', '367', '480', 'coriander', '3', '367', '2', '480']],
 [['c10.jpg', '319', '480', 'coriander', '2', '308', '6', '477']],
 [['c11.jpg', '354', '480', 'coriander', '1', '354', '7', '480']],
 [['c12.jpg', '339', '480', 'coriander', '1', '339', '1', '478']],
 [['c13.jpg', '327', '480', 'coriander', '1', '323', '1', '479']],
 [['c14.jpg', '313', '480', 'coriander', '2', '313', '3', '480']],
 [['c15.jpg', '407', '480', 'coriander', '34', '368', '1', '457']],
 [['c16.jpg', '346', '480', 'coriander', '2', '346', '2', '480']],
 [['c17.jpg', '346', '480', 'coriander', '3', '344', '1', '478']],
 [['c18.jpg', '346', '480', 'coriander', '3', '346', '2', '474']],
 [['c19.jpg', '389', '480', 'coriander', '1', '301', '2', '454']],
 [['c2.jpg', '370', '480', 'coriander', '3', '370', '1', '480']],
 [['c20.jpg', '345', '480', 'coriander', '1', '344', '1', '479']],
 [['c21.jpg', '349', '480', 'coriander', '4', '349', '1', '478']],
 [['c22.jpg', '341', '480', 'coriander', '2', '341', '1', '476']],
 [['c23.jpg', '480', '313', 'coriander', '1', '217', '1', '313']],
 [['c24.jpg', '341', '480', 'coriander', '2', '341', '3', '453']],
 [['c25.jpg', '358', '480', 'coriander', '1', '357', '1', '468']],
 [['c26.jpg', '337', '480', 'coriander', '1', '337', '1', '480']],
 [['c27.jpg', '352', '480', 'coriander', '4', '352', '3', '466']],
 [['c28.jpg', '426', '480', 'coriander', '28', '335', '16', '463']],
 [['c29.jpg', '289', '480', 'coriander', '1', '287', '6', '474']],
 [['c3.jpg', '332', '480', 'coriander', '2', '332', '3', '478']],
 [['c30.jpg', '251', '480', 'coriander', '2', '251', '3', '480']],
 [['c31.jpg', '381', '480', 'coriander', '26', '287', '2', '475']],
 [['c32.jpg', '480', '439', 'coriander', '23', '254', '1', '438']],
 [['c33.jpg', '366', '480', 'coriander', '2', '366', '1', '480']],
 [['c34.jpg', '328', '480', 'coriander', '1', '328', '2', '477']],
 [['c35.jpg', '480', '465', 'coriander', '72', '448', '1', '465']],
 [['c36.jpg', '240', '480', 'coriander', '3', '240', '5', '468']],
 [['c37.jpg', '311', '480', 'coriander', '1', '311', '2', '480']],
 [['c38.jpg', '305', '480', 'coriander', '1', '304', '3', '480']],
 [['c39.jpg', '341', '480', 'coriander', '1', '340', '2', '477']],
 [['c4.jpg', '276', '480', 'coriander', '2', '272', '30', '480']],
 [['c40.jpg', '312', '480', 'coriander', '5', '312', '5', '480']],
 [['c41.jpg', '297', '480', 'coriander', '2', '297', '3', '474']],
 [['c42.jpg', '335', '480', 'coriander', '3', '335', '6', '480']],
 [['c43.jpg', '437', '480', 'coriander', '28', '357', '2', '475']],
 [['c44.jpg', '310', '480', 'coriander', '3', '310', '2', '480']],
 [['c45.jpg', '343', '480', 'coriander', '1', '343', '6', '480']],
 [['c46.jpg', '463', '480', 'coriander', '246', '463', '142', '480']],
 [['c47.jpg', '255', '480', 'coriander', '1', '255', '1', '480']],
 [['c48.jpg', '334', '480', 'coriander', '1', '333', '18', '480']],
 [['c49.jpg', '368', '480', 'coriander', '3', '368', '9', '480']],
 [['c5.jpg', '427', '480', 'coriander', '2', '422', '7', '480']],
 [['c50.jpg', '311', '480', 'coriander', '1', '311', '1', '480']],
 [['c6.jpg', '403', '480', 'coriander', '1', '403', '4', '480']],
 [['c7.jpg', '421', '480', 'coriander', '1', '412', '5', '480']],
 [['c8.jpg', '349', '480', 'coriander', '3', '349', '1', '479']],
 [['c9.jpg', '327', '480', 'coriander', '1', '327', '3', '480']],
 [['g1.jpg', '319', '480', 'garam', '2', '319', '1', '480']],
 [['g10.jpg', '360', '480', 'garam', '2', '359', '3', '469']],
 [['g11.jpg', '480', '467', 'garam', '44', '434', '2', '420']],
 [['g12.jpg', '467', '480', 'garam', '71', '403', '2', '442']],
 [['g13.jpg', '308', '480', 'garam', '1', '308', '1', '480']],
 [['g14.jpg', '278', '480', 'garam', '1', '276', '1', '424']],
 [['g15.jpg', '317', '480', 'garam', '1', '317', '2', '480']],
 [['g16.jpg', '423', '480', 'garam', '1', '423', '1', '480']],
 [['g17.jpg', '480', '472', 'garam', '45', '445', '2', '468']],
 [['g18.jpg', '480', '313', 'garam', '3', '251', '2', '304']],
 [['g19.jpg', '329', '480', 'garam', '2', '329', '1', '480']],
 [['g2.jpg', '402', '480', 'garam', '1', '402', '1', '478']],
 [['g20.jpg', '338', '480', 'garam', '4', '337', '1', '477']],
 [['g21.jpg', '294', '480', 'garam', '2', '294', '1', '480']],
 [['g22.jpg', '353', '480', 'garam', '1', '353', '3', '480']],
 [['g23.jpg', '380', '480', 'garam', '1', '380', '1', '480']],
 [['g24.jpg', '480', '459', 'garam', '176', '480', '5', '404']],
 [['g25.jpg', '480', '480', 'garam', '92', '360', '63', '442']],
 [['g26.jpg', '405', '480', 'garam', '2', '322', '1', '420']],
 [['g27.jpg', '329', '480', 'garam', '3', '329', '1', '480']],
 [['g28.jpg', '298', '480', 'garam', '1', '298', '1', '480']],
 [['g29.jpg', '379', '480', 'garam', '39', '352', '6', '480']],
 [['g3.jpg', '260', '480', 'garam', '1', '256', '2', '405']],
 [['g30.jpg', '312', '480', 'garam', '4', '312', '1', '480']],
 [['g31.jpg', '480', '455', 'garam', '157', '480', '2', '450']],
 [['g32.jpg', '370', '480', 'garam', '11', '362', '14', '470']],
 [['g33.jpg', '351', '480', 'garam', '1', '351', '1', '480']],
 [['g34.jpg', '324', '480', 'garam', '1', '324', '2', '480']],
 [['g35.jpg', '332', '480', 'garam', '3', '332', '2', '478']],
 [['g36.jpg', '348', '480', 'garam', '2', '348', '2', '480']],
 [['g37.jpg', '344', '480', 'garam', '5', '343', '1', '480']],
 [['g38.jpg', '308', '480', 'garam', '1', '308', '1', '480']],
 [['g39.jpg', '459', '480', 'garam', '60', '390', '1', '475']],
 [['g40.jpg', '308', '480', 'garam', '2', '308', '1', '479']],
 [['g41.jpg', '307', '480', 'garam', '2', '307', '5', '480']],
 [['g42.jpg', '357', '480', 'garam', '3', '309', '2', '480']],
 [['g43.jpg', '312', '480', 'garam', '3', '312', '1', '480']],
 [['g44.jpg', '480', '360', 'garam', '20', '451', '13', '336']],
 [['g45.jpg', '351', '480', 'garam', '2', '351', '1', '479']],
 [['g46.jpg', '325', '480', 'garam', '1', '325', '2', '480']],
 [['g47.jpg', '294', '480', 'garam', '34', '252', '1', '476']],
 [['g48.jpg', '375', '480', 'garam', '2', '375', '1', '479']],
 [['g49.jpg', '318', '480', 'garam', '1', '318', '1', '480']],
 [['g5.jpg', '354', '480', 'garam', '2', '354', '2', '480']],
 [['g50.jpg', '430', '480', 'garam', '51', '382', '26', '480']],
 [['g6.jpg', '295', '480', 'garam', '1', '295', '1', '480']],
 [['g7.jpg', '363', '480', 'garam', '1', '363', '1', '480']],
 [['g8.jpg', '373', '480', 'garam', '2', '373', '1', '480']],
 [['g9.jpg', '350', '480', 'garam', '1', '350', '2', '480']],
 [['t1.jpg', '370', '480', 'turmeric', '2', '370', '1', '480']],
 [['t10.jpg', '480', '464', 'turmeric', '1', '295', '1', '464']],
 [['t11.jpg', '457', '480', 'turmeric', '3', '457', '1', '480']],
 [['t12.jpg', '282', '480', 'turmeric', '2', '282', '2', '480']],
 [['t13.jpg', '341', '480', 'turmeric', '3', '341', '2', '480']],
 [['t14.jpg', '368', '480', 'turmeric', '1', '368', '1', '480']],
 [['t15.jpg', '188', '480', 'turmeric', '1', '188', '1', '479']],
 [['t16.jpg', '329', '480', 'turmeric', '2', '329', '1', '480']],
 [['t17.jpg', '480', '338', 'turmeric', '241', '480', '1', '338']],
 [['t18.jpg', '208', '480', 'turmeric', '2', '208', '1', '480']],
 [['t19.jpg', '332', '480', 'turmeric', '1', '332', '2', '480']],
 [['t2.jpg', '421', '480', 'turmeric', '13', '400', '1', '480']],
 [['t20.jpg', '480', '473', 'turmeric', '208', '480', '1', '472']],
 [['t21.jpg', '341', '480', 'turmeric', '1', '341', '1', '480']],
 [['t22.jpg', '468', '480', 'turmeric', '127', '468', '1', '479']],
 [['t23.jpg', '368', '480', 'turmeric', '2', '368', '2', '480']],
 [['t24.jpg', '300', '480', 'turmeric', '2', '300', '1', '480']],
 [['t25.jpg', '480', '471', 'turmeric', '1', '206', '1', '470']],
 [['t26.jpg', '480', '430', 'turmeric', '1', '259', '2', '426']],
 [['t27.jpg', '336', '480', 'turmeric', '2', '329', '1', '479']],
 [['t28.jpg', '441', '480', 'turmeric', '74', '409', '1', '480']],
 [['t29.jpg', '395', '480', 'turmeric', '3', '395', '2', '480']],
 [['t3.jpg', '339', '480', 'turmeric', '1', '339', '1', '480']],
 [['t30.jpg', '329', '480', 'tea', '58', '257', '1', '474']],
 [['t31.jpg', '310', '480', 'turmeric', '2', '310', '1', '480']],
 [['t32.jpg', '236', '480', 'turmeric', '1', '236', '1', '479']],
 [['t33.jpg', '364', '480', 'turmeric', '25', '364', '3', '473']],
 [['t34.jpg', '480', '472', 'turmeric', '83', '397', '3', '472']],
 [['t35.jpg', '480', '313', 'turmeric', '1', '252', '1', '313']],
 [['t36.jpg', '353', '480', 'turmeric', '2', '353', '2', '480']],
 [['t37.jpg', '246', '480', 'turmeric', '1', '246', '3', '480']],
 [['t38.jpg', '325', '480', 'turmeric', '2', '325', '3', '480']],
 [['t39.jpg', '480', '375', 'turmeric', '243', '480', '1', '375']],
 [['t4.jpg', '402', '480', 'turmeric', '1', '402', '1', '480']],
 [['t40.jpg', '343', '480', 'turmeric', '1', '343', '1', '480']],
 [['t41.jpg', '317', '480', 'turmeric', '2', '317', '1', '480']],
 [['t42.jpg', '302', '480', 'turmeric', '2', '302', '1', '480']],
 [['t43.jpg', '345', '480', 'turmeric', '4', '345', '1', '467']],
 [['t44.jpg', '318', '480', 'turmeric', '1', '318', '1', '480']],
 [['t45.jpg', '399', '480', 'turmeric', '2', '399', '1', '480']],
 [['t46.jpg', '333', '480', 'turmeric', '1', '333', '1', '480']],
 [['t47.jpg', '323', '480', 'turmeric', '4', '323', '1', '480']],
 [['t48.jpg', '340', '480', 'turmeric', '1', '340', '2', '480']],
 [['t49.jpg', '328', '480', 'turmeric', '1', '328', '1', '480']],
 [['t5.jpg', '353', '480', 'turmeric', '20', '353', '1', '478']],
 [['t50.jpg', '320', '480', 'turmeric', '2', '320', '3', '480']],
 [['t6.jpg', '329', '480', 'turmeric', '2', '329', '2', '480']],
 [['t7.jpg', '437', '480', 'turmeric', '118', '437', '2', '480']],
 [['t8.jpg', '427', '480', 'turmeric', '2', '427', '1', '480']],
 [['t9.jpg', '350', '480', 'turmeric', '3', '350', '1', '480']]]

In [37]:
data = reduce(lambda x,y : x+y,parser_all)

In [39]:
df = pd.DataFrame(data,columns = ['filename','width','height','name','xmin','xmax','ymin','ymax'])

In [40]:
df.head()

  filename width height       name xmin xmax ymin ymax
0   c1.jpg   367    480  coriander    3  367    2  480
1  c10.jpg   319    480  coriander    2  308    6  477
2  c11.jpg   354    480  coriander    1  354    7  480
3  c12.jpg   339    480  coriander    1  339    1  478
4  c13.jpg   327    480  coriander    1  323    1  479

In [41]:
df.shape

(149, 8)

In [42]:
df['name'].value_counts()

name
coriander    50
garam        49
turmeric     49
tea           1
Name: count, dtype: int64

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   filename  149 non-null    object
 1   width     149 non-null    object
 2   height    149 non-null    object
 3   name      149 non-null    object
 4   xmin      149 non-null    object
 5   xmax      149 non-null    object
 6   ymin      149 non-null    object
 7   ymax      149 non-null    object
dtypes: object(8)
memory usage: 9.4+ KB

In [45]:
cols = ['width','height','xmin','xmax','ymin','ymax']
df[cols] = df[cols].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   filename  149 non-null    object
 1   width     149 non-null    int64
 2   height    149 non-null    int64
 3   name      149 non-null    object
 4   xmin      149 non-null    int64
 5   xmax      149 non-null    int64
 6   ymin      149 non-null    int64
 7   ymax      149 non-null    int64
dtypes: int64(6), object(2)
memory usage: 9.4+ KB

In [46]:
df['center_x'] = ((df['xmax']+df['xmin'])/2)/df['width']
df['center_y'] = ((df['ymax']+df['ymin'])/2)/df['height']

df['w'] = (df['xmax']-df['xmin'])/df['width']
df['h'] = (df['ymax']-df['ymin'])/df['height']

In [47]:
df.head()

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h
0,c1.jpg,367,480,coriander,3,367,2,480,0.504087,0.502083,0.991826,0.995833
1,c10.jpg,319,480,coriander,2,308,6,477,0.485893,0.503125,0.959248,0.981250
2,c11.jpg,354,480,coriander,1,354,7,480,0.501412,0.507292,0.997175,0.985417
3,c12.jpg,339,480,coriander,1,339,1,478,0.501475,0.498958,0.997050,0.993750
4,c13.jpg,327,480,coriander,1,323,1,479,0.495413,0.500000,0.984709,0.995833

In [48]:
images = df['filename'].unique()

In [50]:
len(images)

149

In [53]:
img_df = pd.DataFrame(images,columns=['filename'])
img_train = tuple( img_df.sample(frac=0.8)['filename'])

In [54]:
img_train

('t42.jpg',
 't44.jpg',
 'g27.jpg',
 't24.jpg',
 'g17.jpg',
 'g32.jpg',
 'c8.jpg',
 't6.jpg',
 't3.jpg',
 'c28.jpg',
 'g30.jpg',
 't50.jpg',
 't41.jpg',
 'g25.jpg',
 'g46.jpg',
 'g42.jpg',
 'g34.jpg',
 't45.jpg',
 'g23.jpg',
 't37.jpg',
 'c33.jpg',
 'g19.jpg',
 't27.jpg',
 'g16.jpg',
 'g28.jpg',
 't31.jpg',
 'c24.jpg',
 'c35.jpg',
 'c9.jpg',
 'c21.jpg',
 't34.jpg',
 'c4.jpg',
 'c50.jpg',
 'g48.jpg',
 'c26.jpg',
 'c5.jpg',
 'c41.jpg',
 't17.jpg',
 'g3.jpg',
 'c14.jpg',
 'g8.jpg',
 't11.jpg',
 'g2.jpg',
 'g44.jpg',
 'c7.jpg',
 't32.jpg',
 'c27.jpg',
 'c45.jpg',
 't38.jpg',
 'c42.jpg',
 'c17.jpg',
 'g21.jpg',
 'g47.jpg',
 'c47.jpg',
 'c13.jpg',
 'c44.jpg',
 't29.jpg',
 'g14.jpg',
 'g45.jpg',
 'c2.jpg',
 't19.jpg',
 't4.jpg',
 'c31.jpg',
 'g31.jpg',
 't48.jpg',
 'g15.jpg',
 'g39.jpg',
 't23.jpg',
 't28.jpg',
 'g13.jpg',
 'c19.jpg',
 'g9.jpg',
 'g40.jpg',
 'c20.jpg',
 't21.jpg',
 't22.jpg',
 't5.jpg',
 't35.jpg',
 'c48.jpg',
 't33.jpg',
 'g6.jpg',
 'c37.jpg',
 'g11.jpg',
 'c15.jpg',
 't7.jpg',
 'c16.jpg',
 'g35.jpg',
 'g43.jpg',
 'c39.jpg',
 't16.jpg',
 't43.jpg',
 'c11.jpg',
 't2.jpg',
 't36.jpg',
 'g18.jpg',
 't8.jpg',
 't47.jpg',
 'c46.jpg',
 'g37.jpg',
 'c40.jpg',
 'g29.jpg',
 'c22.jpg',
 'c43.jpg',
 't15.jpg',
 'g20.jpg',
 'g24.jpg',
 't49.jpg',
 'c32.jpg',
 'c6.jpg',
 't25.jpg',
 'g7.jpg',
 't18.jpg',
 't13.jpg',
 't10.jpg',
 'c1.jpg',
 't12.jpg',
 'c38.jpg',
 'c23.jpg',
 't14.jpg')

In [55]:
img_test = tuple(img_df.query(f'filename not in {img_train}')['filename'])

In [57]:
len(img_test), len(img_train)

(30, 119)

In [58]:
train_df = df.query(f'filename in {img_train}')
test_df = df.query(f'filename in {img_test}')

In [59]:
train_df.head()

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h
0,c1.jpg,367,480,coriander,3,367,2,480,0.504087,0.502083,0.991826,0.995833
2,c11.jpg,354,480,coriander,1,354,7,480,0.501412,0.507292,0.997175,0.985417
4,c13.jpg,327,480,coriander,1,323,1,479,0.495413,0.500000,0.984709,0.995833
5,c14.jpg,313,480,coriander,2,313,3,480,0.503195,0.503125,0.993610,0.993750
6,c15.jpg,407,480,coriander,34,368,1,457,0.493857,0.477083,0.820639,0.950000

In [60]:
test_df.head()

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h
1,c10.jpg,319,480,coriander,2,308,6,477,0.485893,0.503125,0.959248,0.981250
3,c12.jpg,339,480,coriander,1,339,1,478,0.501475,0.498958,0.997050,0.993750
9,c18.jpg,346,480,coriander,3,346,2,474,0.504335,0.495833,0.991329,0.983333
17,c25.jpg,358,480,coriander,1,357,1,468,0.500000,0.488542,0.994413,0.972917
21,c29.jpg,289,480,coriander,1,287,6,474,0.498270,0.500000,0.989619,0.975000

In [61]:
def label_encoding(x):
    labels = {'coriander':0, 'tea':1, 'garam':2, 'turmeric':3}
    return labels[x]

In [108]:
train_df.loc[:, 'id'] = train_df['name'].apply(label_encoding)
test_df.loc[:, 'id'] = test_df['name'].apply(label_encoding)

In [63]:
train_df.head(10)

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h,id
0,c1.jpg,367,480,coriander,3,367,2,480,0.504087,0.502083,0.991826,0.995833,0
2,c11.jpg,354,480,coriander,1,354,7,480,0.501412,0.507292,0.997175,0.985417,0
4,c13.jpg,327,480,coriander,1,323,1,479,0.495413,0.500000,0.984709,0.995833,0
5,c14.jpg,313,480,coriander,2,313,3,480,0.503195,0.503125,0.993610,0.993750,0
6,c15.jpg,407,480,coriander,34,368,1,457,0.493857,0.477083,0.820639,0.950000,0
7,c16.jpg,346,480,coriander,2,346,2,480,0.502890,0.502083,0.994220,0.995833,0
8,c17.jpg,346,480,coriander,3,344,1,478,0.501445,0.498958,0.985549,0.993750,0
10,c19.jpg,389,480,coriander,1,301,2,454,0.388175,0.475000,0.771208,0.941667,0
11,c2.jpg,370,480,coriander,3,370,1,480,0.504054,0.501042,0.991892,0.997917,0
12,c20.jpg,345,480,coriander,1,344,1,479,0.500000,0.500000,0.994203,0.995833,0

In [64]:
import os
from shutil import move

In [113]:
train_folder = './data_images/train'
test_folder = './data_images/test'

os.mkdir(train_folder)
os.mkdir(test_folder)

FileExistsError: [WinError 183] Cannot create a file when that file already exists: './data_images/train'

In [114]:
cols = ['filename','id', 'center_x','center_y', 'w', 'h']
groupby_obj_train = train_df[cols].groupby('filename')
groupby_obj_test = test_df[cols].groupby('filename')

In [121]:
from shutil import move
import os

def save_data(filename, folder_path, group_obj):
    # Construct source and destination file paths
    src = os.path.join('data_images', filename)
    dst = os.path.join(folder_path, filename)

    # Check if source file exists before moving
    if os.path.exists(src):
        move(src, dst)
        print(f"Moved {src} to {dst}")
    else:
        print(f"File not found: {src}")
        return  # Exit the function if file doesn't exist

    # Save the text file as usual
    text_filename = os.path.join(folder_path, os.path.splitext(filename)[0] + '.txt')
    group_obj.get_group(filename).set_index('filename').to_csv(text_filename, sep=' ', index=False, header=False)

In [116]:
filename_series = pd.Series(groupby_obj_train.groups.keys())

In [122]:
filename_series.apply(save_data,args=(train_folder,groupby_obj_train))

File not found: data_images\c1.jpg
File not found: data_images\c11.jpg
File not found: data_images\c13.jpg
File not found: data_images\c14.jpg
File not found: data_images\c15.jpg
File not found: data_images\c16.jpg
File not found: data_images\c17.jpg
File not found: data_images\c19.jpg
File not found: data_images\c2.jpg
File not found: data_images\c20.jpg
File not found: data_images\c21.jpg
File not found: data_images\c22.jpg
File not found: data_images\c23.jpg
File not found: data_images\c24.jpg
File not found: data_images\c26.jpg
File not found: data_images\c27.jpg
File not found: data_images\c28.jpg
File not found: data_images\c31.jpg
File not found: data_images\c32.jpg
File not found: data_images\c33.jpg
File not found: data_images\c35.jpg
File not found: data_images\c37.jpg
File not found: data_images\c38.jpg
File not found: data_images\c39.jpg
File not found: data_images\c4.jpg
File not found: data_images\c40.jpg
File not found: data_images\c41.jpg
File not found: data_images\c42.jpg
File not found: data_images\c43.jpg
File not found: data_images\c44.jpg
File not found: data_images\c45.jpg
File not found: data_images\c46.jpg
File not found: data_images\c47.jpg
File not found: data_images\c48.jpg
File not found: data_images\c5.jpg
File not found: data_images\c50.jpg
File not found: data_images\c6.jpg
File not found: data_images\c7.jpg
File not found: data_images\c8.jpg
File not found: data_images\c9.jpg
File not found: data_images\g11.jpg
File not found: data_images\g13.jpg
File not found: data_images\g14.jpg
File not found: data_images\g15.jpg
File not found: data_images\g16.jpg
File not found: data_images\g17.jpg
File not found: data_images\g18.jpg
File not found: data_images\g19.jpg
File not found: data_images\g2.jpg
File not found: data_images\g20.jpg
File not found: data_images\g21.jpg
File not found: data_images\g23.jpg
File not found: data_images\g24.jpg
File not found: data_images\g25.jpg
File not found: data_images\g27.jpg
File not found: data_images\g28.jpg
File not found: data_images\g29.jpg
File not found: data_images\g3.jpg
File not found: data_images\g30.jpg
File not found: data_images\g31.jpg
File not found: data_images\g32.jpg
File not found: data_images\g34.jpg
File not found: data_images\g35.jpg
File not found: data_images\g37.jpg
File not found: data_images\g39.jpg
File not found: data_images\g40.jpg
File not found: data_images\g42.jpg
File not found: data_images\g43.jpg
File not found: data_images\g44.jpg
File not found: data_images\g45.jpg
File not found: data_images\g46.jpg
File not found: data_images\g47.jpg
File not found: data_images\g48.jpg
File not found: data_images\g6.jpg
File not found: data_images\g7.jpg
File not found: data_images\g8.jpg
File not found: data_images\g9.jpg
File not found: data_images\t10.jpg
File not found: data_images\t11.jpg
File not found: data_images\t12.jpg
File not found: data_images\t13.jpg
File not found: data_images\t14.jpg
File not found: data_images\t15.jpg
File not found: data_images\t16.jpg
File not found: data_images\t17.jpg
File not found: data_images\t18.jpg
File not found: data_images\t19.jpg
File not found: data_images\t2.jpg
File not found: data_images\t21.jpg
File not found: data_images\t22.jpg
File not found: data_images\t23.jpg
File not found: data_images\t24.jpg
File not found: data_images\t25.jpg
File not found: data_images\t27.jpg
File not found: data_images\t28.jpg
File not found: data_images\t29.jpg
File not found: data_images\t3.jpg
File not found: data_images\t31.jpg
File not found: data_images\t32.jpg
File not found: data_images\t33.jpg
File not found: data_images\t34.jpg
File not found: data_images\t35.jpg
File not found: data_images\t36.jpg
File not found: data_images\t37.jpg
File not found: data_images\t38.jpg
File not found: data_images\t4.jpg
File not found: data_images\t41.jpg
File not found: data_images\t42.jpg
File not found: data_images\t43.jpg
File not found: data_images\t44.jpg
File not found: data_images\t45.jpg
File not found: data_images\t47.jpg
File not found: data_images\t48.jpg
File not found: data_images\t49.jpg
File not found: data_images\t5.jpg
File not found: data_images\t50.jpg
File not found: data_images\t6.jpg
File not found: data_images\t7.jpg
File not found: data_images\t8.jpg

0      None
1      None
2      None
3      None
4      None
       ...
114    None
115    None
116    None
117    None
118    None
Length: 119, dtype: object

In [124]:
filename_series_test=pd.Series(groupby_obj_test.groups.keys())
filename_series_test.apply(save_data,args=(test_folder,groupby_obj_test))

File not found: data_images\c10.jpg
Moved data_images\c12.jpg to ./data_images/test\c12.jpg
Moved data_images\c18.jpg to ./data_images/test\c18.jpg
Moved data_images\c25.jpg to ./data_images/test\c25.jpg
Moved data_images\c29.jpg to ./data_images/test\c29.jpg
Moved data_images\c3.jpg to ./data_images/test\c3.jpg
Moved data_images\c30.jpg to ./data_images/test\c30.jpg
Moved data_images\c34.jpg to ./data_images/test\c34.jpg
Moved data_images\c36.jpg to ./data_images/test\c36.jpg
Moved data_images\c49.jpg to ./data_images/test\c49.jpg
Moved data_images\g1.jpg to ./data_images/test\g1.jpg
Moved data_images\g10.jpg to ./data_images/test\g10.jpg
Moved data_images\g12.jpg to ./data_images/test\g12.jpg
Moved data_images\g22.jpg to ./data_images/test\g22.jpg
Moved data_images\g26.jpg to ./data_images/test\g26.jpg
Moved data_images\g33.jpg to ./data_images/test\g33.jpg
Moved data_images\g36.jpg to ./data_images/test\g36.jpg
Moved data_images\g38.jpg to ./data_images/test\g38.jpg
Moved data_images\g41.jpg to ./data_images/test\g41.jpg
Moved data_images\g49.jpg to ./data_images/test\g49.jpg
Moved data_images\g5.jpg to ./data_images/test\g5.jpg
Moved data_images\g50.jpg to ./data_images/test\g50.jpg
Moved data_images\t1.jpg to ./data_images/test\t1.jpg
Moved data_images\t20.jpg to ./data_images/test\t20.jpg
Moved data_images\t26.jpg to ./data_images/test\t26.jpg
Moved data_images\t30.jpg to ./data_images/test\t30.jpg
Moved data_images\t39.jpg to ./data_images/test\t39.jpg
Moved data_images\t40.jpg to ./data_images/test\t40.jpg
Moved data_images\t46.jpg to ./data_images/test\t46.jpg
Moved data_images\t9.jpg to ./data_images/test\t9.jpg

0     None
1     None
2     None
3     None
4     None
5     None
6     None
7     None
8     None
9     None
10    None
11    None
12    None
13    None
14    None
15    None
16    None
17    None
18    None
19    None
20    None
21    None
22    None
23    None
24    None
25    None
26    None
27    None
28    None
29    None
dtype: object